name: instabug_dart_io_http_client
description:
  This package is an add-on to instabug_flutter. It intercepts any requests performed
  using the dart:io package HttpClient and attaches them to the report that will be sent to the dashboard.
version: 1.0.0
homepage: https://github.com/Instabug/Instabug-Flutter#readme

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  instabug_flutter: ^11.0.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.2.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
