version: 2
jobs:
   test:
    docker:
      - image: cirrusci/flutter:2.10.5
    steps:
      - checkout
      - run: flutter doctor
      - run: pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: dartanalyzer --options analysis_options.yaml --fatal-warnings lib

workflows:
  version: 2
  build-test:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master     